// CMS_DATA_START — auto-generated by Portfolio CMS, do not edit manually
const CMS_DATA = {
  "hero": {
    "tag": "Software Developer · Cairo, Egypt",
    "name": "Muhammad",
    "surname": "Rashwan",
    "title": "MERN Full-stack Developer Who Thinks Like a Systems Architect.",
    "subtitle": "Junior by title. Elite by execution.",
    "statement": "The job won't be well done.\nIt will be the nearest to perfection.\n\nI don't build pages. I engineer experiences.",
    "ctaEmail": "muhammadrashwan1101@gmail.com",
    "coords": "30.0444° N, 31.2357° E · Cairo · Egypt"
  },
  "about": {
    "content": [
      "Most developers learn from tutorials. I was trained inside a Military Academy environment. 9 months. Intensive. Structured. No excuses.",
      "I'm an Electrical Engineering graduate who chose software — not because it was easier, but because it demanded the same precision. I understand systems. I understand failure modes. I understand what it costs when things break.",
      "That background doesn't just shape how I write code. It shapes how I think about code.",
      "Deadlines are targets. Architecture is strategy. Clean code is discipline — not preference."
    ],
    "pillars": [
      {
        "num": "01",
        "title": "Discipline",
        "desc": "Military-grade time management. Commitments are kept. Timelines are non-negotiable. Every PR is a responsibility."
      },
      {
        "num": "02",
        "title": "Systems Thinking",
        "desc": "Electrical engineering taught me to see the whole circuit — not just one component. I see the system before I touch the code."
      },
      {
        "num": "03",
        "title": "Execution",
        "desc": "Ideas are cheap. Implementation is everything. I ship. I iterate. I deliver."
      },
      {
        "num": "04",
        "title": "Ownership",
        "desc": "I don't hand off problems. I absorb them. The feature is mine until it's in production and bulletproof."
      }
    ]
  },
  "skills": [
    {
      "label": "Front-End Development",
      "title": "Interface Engineering",
      "tags": [
        "React",
        "Tailwind CSS",
        "Redux",
        "Context API",
        "TypeScript",
        "HTML5",
        "CSS3"
      ]
    },
    {
      "label": "Back-End & Software Development",
      "title": "System & Logic",
      "tags": [
        "C++",
        "Node.js",
        "REST APIs",
        "Async Programming",
        "OOP",
        "Data Structures"
      ]
    },
    {
      "label": "DevOps",
      "title": "Cloud & Deployment",
      "tags": [
        "AWS",
        "CI/CD",
        "Vercel",
        "Git",
        "GitHub Actions",
        "Netlify"
      ]
    },
    {
      "label": "Miscellaneous",
      "title": "Advanced Integrations",
      "tags": [
        "Leaflet Maps",
        "Geolocation",
        "Geofencing",
        "Image Recognition APIs",
        "Real-Time Data",
        "WebSockets"
      ]
    }
  ],
  "projects": [
    {
      "name": "Sanad",
      "subtitle": "Alzheimer & Dementia Monitoring System",
      "description": "This isn't a demo project. This is purpose-driven engineering.\n\nSanad was built for families living in fear — caregivers who can't watch every second. Patients who wander. Families who panic. Real people. Real stakes.\n\nI engineered a system that brings them peace of mind — through precision geolocation, intelligent geofencing, and real-time caregiver alerts. It doesn't look like a healthcare tool. It functions like a lifeline.",
      "liveUrl": "https://egsanad.vercel.app/",
      "repoUrl": "https://github.com/muhammadRashwan1101/S.Project",
      "features": [
        {
          "title": "Real-Time Geolocation",
          "desc": "Live patient tracking with sub-minute update cycles. Always on. Always accurate."
        },
        {
          "title": "Geofencing Alerts",
          "desc": "Custom safety zones. Instant notifications when boundaries are broken. Zero tolerance for blind spots."
        },
        {
          "title": "Caregiver Dashboard",
          "desc": "Multi-patient monitoring interface. Clean. Scannable. Decisive. Designed for urgency."
        },
        {
          "title": "Social Impact Engineering",
          "desc": "Not built to impress recruiters. Built to protect Alzheimer patients across Egypt."
        },
        {
          "title": "Stack",
          "desc": "React · Leaflet Maps · REST APIs · Real-Time Data · Vercel"
        }
      ]
    },
    {
      "name": "VisioCreate",
      "subtitle": "E-Commerce Clothing Store",
      "description": "A modern e-commerce clothing store demo designed to showcase a clean shopping experience with a responsive and user-friendly interface. The project focuses on presenting products in an organized and visually appealing way while simulating the core functionality of a real online fashion store.\n\nThe application allows users to browse clothing categories, explore product details, and navigate seamlessly across different sections through a fast and responsive UI optimized for both desktop and mobile devices.\n\nKey Features:\n\nModern and responsive design\nOrganized product catalog and categories\nDedicated product detail pages\nSmooth and intuitive user experience\nMobile-friendly interface\nClean front-end structure and scalable layout\n\nThis project demonstrates practical experience in front-end web development, responsive design principles, and building modern e-commerce user interfaces.",
      "liveUrl": "https://visiocreate.vercel.app/",
      "repoUrl": "",
      "features": [
        {
          "title": "Modern Product Showcase",
          "desc": "Clean product presentation with visually organized clothing collections designed for smooth browsing and fast discovery."
        },
        {
          "title": "Responsive Store Experience",
          "desc": "Fully adaptive layout optimized for desktop, tablet, and mobile devices. Consistent experience across all screen sizes."
        },
        {
          "title": "Product Details Interface",
          "desc": "Dedicated pages for each item featuring product imagery, descriptions, pricing, and streamlined navigation."
        },
        {
          "title": "Category-Based Navigation",
          "desc": "Structured clothing sections that simplify product exploration and improve overall shopping flow."
        },
        {
          "title": "Smooth User Interaction",
          "desc": "Fast page transitions, intuitive navigation, and a minimal interface focused on usability and accessibility."
        },
        {
          "title": "Modern UI Design",
          "desc": "Contemporary storefront aesthetics with balanced spacing, clean typography, and visually engaging layouts."
        },
        {
          "title": "Deployment & Hosting",
          "desc": "Live deployment pipeline configured for production hosting with optimized frontend delivery through Vercel."
        },
        {
          "title": "Stack",
          "desc": "React.js · Vite · Responsive UI · Frontend Architecture · Vercel Deployment"
        }
      ]
    }
  ],
  "experience": [
    {
      "date": "2023 — 2024",
      "org": "Military Academy Environment — Software Dev Diploma",
      "role": "Full-Stack Software Development Trainee (Military Program)",
      "bullets": [
        "9-month diploma executed inside a military-grade structured curriculum. Zero tolerance for mediocrity.",
        "Full-stack exposure with deep focus on React, Node.js, and system architecture.",
        "Stretching Full-stack skills to include DevOps, Aws Cloud Computing, and system architecture.",
        "Graduated with production-ready skills — not theoretical ones. Every module was tied to real deliverables.",
        "Developed the discipline to build under pressure, communicate with precision, and lead through complexity."
      ]
    },
    {
      "date": "2024",
      "org": "IEEE Aswan Student Branch",
      "role": "Front-End Developer — BeIn Camp v6",
      "bullets": [
        "Sole front-end engineer on the official registration platform for BeIn Camp v6 — an IEEE regional event.",
        "Architected and delivered the full UI in React, Next.js, and Redux — from wireframe to production.",
        "Handled real user traffic (100+ registrations) with robust multi-step validation and state management.",
        "Owned the entire front-end pipeline. No handoffs. No excuses. Launched on schedule."
      ]
    }
  ],
  "education": [
    {
      "icon": "BE",
      "title": "Bachelor of Engineering — Energy & Electrical Power",
      "org": "Faculty of Engineering",
      "detail": "The discipline. The systems thinking. The foundation everything is built on."
    },
    {
      "icon": "UD",
      "title": "Front-End Web Development Nanodegree",
      "org": "Udacity",
      "detail": "Industry-grade curriculum. Projects over theory. Reviewed by professionals."
    },
    {
      "icon": "AWS",
      "title": "AWS Cloud Practitioner Trained",
      "org": "Amazon Web Services",
      "detail": "Cloud-aware by design. I understand what runs the infrastructure behind the UI."
    },
    {
      "icon": "MT",
      "title": "Meta Professional Front-End",
      "org": "Meta · Coursera",
      "detail": "Industry perspective from the team that builds at scale. Applied from day one."
    }
  ],
  "contact": {
    "email": "muhammadrashwan1101@gmail.com",
    "whatsapp": "+201552497677",
    "github": "https://github.com/muhammadRashwan1101",
    "linkedin": "https://www.linkedin.com/in/muhammad-rashwan/",
    "extraLinks": [],
    "closingLine1": "If you want average,",
    "closingLine2": "I'm not your developer.",
    "openTo": "I'm currently open to front-end and full-stack roles, product-focused teams, and problems worth solving."
  }
};
// CMS_DATA_END

const DATA = (typeof CMS_DATA !== 'undefined') ? CMS_DATA : FALLBACK_DATA;

const nav = document.getElementById("nav");
      window.addEventListener("scroll", () => {
        nav.classList.toggle("scrolled", window.scrollY > 50);
      });

      // Reveal on scroll
      const reveals = document.querySelectorAll(".reveal");
      const observer = new IntersectionObserver(
        (entries) => {
          entries.forEach((entry, i) => {
            if (entry.isIntersecting) {
              setTimeout(() => {
                entry.target.classList.add("visible");
              }, 100);
            }
          });
        },
        { threshold: 0.1 },
      );
      reveals.forEach((el) => observer.observe(el));
